###################################################################

# Created by write_sdc on Sat Apr 25 00:49:30 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0 [get_ports weight_load_done]
set_load -pin_load 0 [get_ports {tpu_out[0][31]}]
set_load -pin_load 0 [get_ports {tpu_out[0][30]}]
set_load -pin_load 0 [get_ports {tpu_out[0][29]}]
set_load -pin_load 0 [get_ports {tpu_out[0][28]}]
set_load -pin_load 0 [get_ports {tpu_out[0][27]}]
set_load -pin_load 0 [get_ports {tpu_out[0][26]}]
set_load -pin_load 0 [get_ports {tpu_out[0][25]}]
set_load -pin_load 0 [get_ports {tpu_out[0][24]}]
set_load -pin_load 0 [get_ports {tpu_out[0][23]}]
set_load -pin_load 0 [get_ports {tpu_out[0][22]}]
set_load -pin_load 0 [get_ports {tpu_out[0][21]}]
set_load -pin_load 0 [get_ports {tpu_out[0][20]}]
set_load -pin_load 0 [get_ports {tpu_out[0][19]}]
set_load -pin_load 0 [get_ports {tpu_out[0][18]}]
set_load -pin_load 0 [get_ports {tpu_out[0][17]}]
set_load -pin_load 0 [get_ports {tpu_out[0][16]}]
set_load -pin_load 0 [get_ports {tpu_out[0][15]}]
set_load -pin_load 0 [get_ports {tpu_out[0][14]}]
set_load -pin_load 0 [get_ports {tpu_out[0][13]}]
set_load -pin_load 0 [get_ports {tpu_out[0][12]}]
set_load -pin_load 0 [get_ports {tpu_out[0][11]}]
set_load -pin_load 0 [get_ports {tpu_out[0][10]}]
set_load -pin_load 0 [get_ports {tpu_out[0][9]}]
set_load -pin_load 0 [get_ports {tpu_out[0][8]}]
set_load -pin_load 0 [get_ports {tpu_out[0][7]}]
set_load -pin_load 0 [get_ports {tpu_out[0][6]}]
set_load -pin_load 0 [get_ports {tpu_out[0][5]}]
set_load -pin_load 0 [get_ports {tpu_out[0][4]}]
set_load -pin_load 0 [get_ports {tpu_out[0][3]}]
set_load -pin_load 0 [get_ports {tpu_out[0][2]}]
set_load -pin_load 0 [get_ports {tpu_out[0][1]}]
set_load -pin_load 0 [get_ports {tpu_out[0][0]}]
set_load -pin_load 0 [get_ports {tpu_out[1][31]}]
set_load -pin_load 0 [get_ports {tpu_out[1][30]}]
set_load -pin_load 0 [get_ports {tpu_out[1][29]}]
set_load -pin_load 0 [get_ports {tpu_out[1][28]}]
set_load -pin_load 0 [get_ports {tpu_out[1][27]}]
set_load -pin_load 0 [get_ports {tpu_out[1][26]}]
set_load -pin_load 0 [get_ports {tpu_out[1][25]}]
set_load -pin_load 0 [get_ports {tpu_out[1][24]}]
set_load -pin_load 0 [get_ports {tpu_out[1][23]}]
set_load -pin_load 0 [get_ports {tpu_out[1][22]}]
set_load -pin_load 0 [get_ports {tpu_out[1][21]}]
set_load -pin_load 0 [get_ports {tpu_out[1][20]}]
set_load -pin_load 0 [get_ports {tpu_out[1][19]}]
set_load -pin_load 0 [get_ports {tpu_out[1][18]}]
set_load -pin_load 0 [get_ports {tpu_out[1][17]}]
set_load -pin_load 0 [get_ports {tpu_out[1][16]}]
set_load -pin_load 0 [get_ports {tpu_out[1][15]}]
set_load -pin_load 0 [get_ports {tpu_out[1][14]}]
set_load -pin_load 0 [get_ports {tpu_out[1][13]}]
set_load -pin_load 0 [get_ports {tpu_out[1][12]}]
set_load -pin_load 0 [get_ports {tpu_out[1][11]}]
set_load -pin_load 0 [get_ports {tpu_out[1][10]}]
set_load -pin_load 0 [get_ports {tpu_out[1][9]}]
set_load -pin_load 0 [get_ports {tpu_out[1][8]}]
set_load -pin_load 0 [get_ports {tpu_out[1][7]}]
set_load -pin_load 0 [get_ports {tpu_out[1][6]}]
set_load -pin_load 0 [get_ports {tpu_out[1][5]}]
set_load -pin_load 0 [get_ports {tpu_out[1][4]}]
set_load -pin_load 0 [get_ports {tpu_out[1][3]}]
set_load -pin_load 0 [get_ports {tpu_out[1][2]}]
set_load -pin_load 0 [get_ports {tpu_out[1][1]}]
set_load -pin_load 0 [get_ports {tpu_out[1][0]}]
set_load -pin_load 0 [get_ports {tpu_out[2][31]}]
set_load -pin_load 0 [get_ports {tpu_out[2][30]}]
set_load -pin_load 0 [get_ports {tpu_out[2][29]}]
set_load -pin_load 0 [get_ports {tpu_out[2][28]}]
set_load -pin_load 0 [get_ports {tpu_out[2][27]}]
set_load -pin_load 0 [get_ports {tpu_out[2][26]}]
set_load -pin_load 0 [get_ports {tpu_out[2][25]}]
set_load -pin_load 0 [get_ports {tpu_out[2][24]}]
set_load -pin_load 0 [get_ports {tpu_out[2][23]}]
set_load -pin_load 0 [get_ports {tpu_out[2][22]}]
set_load -pin_load 0 [get_ports {tpu_out[2][21]}]
set_load -pin_load 0 [get_ports {tpu_out[2][20]}]
set_load -pin_load 0 [get_ports {tpu_out[2][19]}]
set_load -pin_load 0 [get_ports {tpu_out[2][18]}]
set_load -pin_load 0 [get_ports {tpu_out[2][17]}]
set_load -pin_load 0 [get_ports {tpu_out[2][16]}]
set_load -pin_load 0 [get_ports {tpu_out[2][15]}]
set_load -pin_load 0 [get_ports {tpu_out[2][14]}]
set_load -pin_load 0 [get_ports {tpu_out[2][13]}]
set_load -pin_load 0 [get_ports {tpu_out[2][12]}]
set_load -pin_load 0 [get_ports {tpu_out[2][11]}]
set_load -pin_load 0 [get_ports {tpu_out[2][10]}]
set_load -pin_load 0 [get_ports {tpu_out[2][9]}]
set_load -pin_load 0 [get_ports {tpu_out[2][8]}]
set_load -pin_load 0 [get_ports {tpu_out[2][7]}]
set_load -pin_load 0 [get_ports {tpu_out[2][6]}]
set_load -pin_load 0 [get_ports {tpu_out[2][5]}]
set_load -pin_load 0 [get_ports {tpu_out[2][4]}]
set_load -pin_load 0 [get_ports {tpu_out[2][3]}]
set_load -pin_load 0 [get_ports {tpu_out[2][2]}]
set_load -pin_load 0 [get_ports {tpu_out[2][1]}]
set_load -pin_load 0 [get_ports {tpu_out[2][0]}]
set_load -pin_load 0 [get_ports {tpu_out[3][31]}]
set_load -pin_load 0 [get_ports {tpu_out[3][30]}]
set_load -pin_load 0 [get_ports {tpu_out[3][29]}]
set_load -pin_load 0 [get_ports {tpu_out[3][28]}]
set_load -pin_load 0 [get_ports {tpu_out[3][27]}]
set_load -pin_load 0 [get_ports {tpu_out[3][26]}]
set_load -pin_load 0 [get_ports {tpu_out[3][25]}]
set_load -pin_load 0 [get_ports {tpu_out[3][24]}]
set_load -pin_load 0 [get_ports {tpu_out[3][23]}]
set_load -pin_load 0 [get_ports {tpu_out[3][22]}]
set_load -pin_load 0 [get_ports {tpu_out[3][21]}]
set_load -pin_load 0 [get_ports {tpu_out[3][20]}]
set_load -pin_load 0 [get_ports {tpu_out[3][19]}]
set_load -pin_load 0 [get_ports {tpu_out[3][18]}]
set_load -pin_load 0 [get_ports {tpu_out[3][17]}]
set_load -pin_load 0 [get_ports {tpu_out[3][16]}]
set_load -pin_load 0 [get_ports {tpu_out[3][15]}]
set_load -pin_load 0 [get_ports {tpu_out[3][14]}]
set_load -pin_load 0 [get_ports {tpu_out[3][13]}]
set_load -pin_load 0 [get_ports {tpu_out[3][12]}]
set_load -pin_load 0 [get_ports {tpu_out[3][11]}]
set_load -pin_load 0 [get_ports {tpu_out[3][10]}]
set_load -pin_load 0 [get_ports {tpu_out[3][9]}]
set_load -pin_load 0 [get_ports {tpu_out[3][8]}]
set_load -pin_load 0 [get_ports {tpu_out[3][7]}]
set_load -pin_load 0 [get_ports {tpu_out[3][6]}]
set_load -pin_load 0 [get_ports {tpu_out[3][5]}]
set_load -pin_load 0 [get_ports {tpu_out[3][4]}]
set_load -pin_load 0 [get_ports {tpu_out[3][3]}]
set_load -pin_load 0 [get_ports {tpu_out[3][2]}]
set_load -pin_load 0 [get_ports {tpu_out[3][1]}]
set_load -pin_load 0 [get_ports {tpu_out[3][0]}]
set_load -pin_load 0 [get_ports {tpu_out[4][31]}]
set_load -pin_load 0 [get_ports {tpu_out[4][30]}]
set_load -pin_load 0 [get_ports {tpu_out[4][29]}]
set_load -pin_load 0 [get_ports {tpu_out[4][28]}]
set_load -pin_load 0 [get_ports {tpu_out[4][27]}]
set_load -pin_load 0 [get_ports {tpu_out[4][26]}]
set_load -pin_load 0 [get_ports {tpu_out[4][25]}]
set_load -pin_load 0 [get_ports {tpu_out[4][24]}]
set_load -pin_load 0 [get_ports {tpu_out[4][23]}]
set_load -pin_load 0 [get_ports {tpu_out[4][22]}]
set_load -pin_load 0 [get_ports {tpu_out[4][21]}]
set_load -pin_load 0 [get_ports {tpu_out[4][20]}]
set_load -pin_load 0 [get_ports {tpu_out[4][19]}]
set_load -pin_load 0 [get_ports {tpu_out[4][18]}]
set_load -pin_load 0 [get_ports {tpu_out[4][17]}]
set_load -pin_load 0 [get_ports {tpu_out[4][16]}]
set_load -pin_load 0 [get_ports {tpu_out[4][15]}]
set_load -pin_load 0 [get_ports {tpu_out[4][14]}]
set_load -pin_load 0 [get_ports {tpu_out[4][13]}]
set_load -pin_load 0 [get_ports {tpu_out[4][12]}]
set_load -pin_load 0 [get_ports {tpu_out[4][11]}]
set_load -pin_load 0 [get_ports {tpu_out[4][10]}]
set_load -pin_load 0 [get_ports {tpu_out[4][9]}]
set_load -pin_load 0 [get_ports {tpu_out[4][8]}]
set_load -pin_load 0 [get_ports {tpu_out[4][7]}]
set_load -pin_load 0 [get_ports {tpu_out[4][6]}]
set_load -pin_load 0 [get_ports {tpu_out[4][5]}]
set_load -pin_load 0 [get_ports {tpu_out[4][4]}]
set_load -pin_load 0 [get_ports {tpu_out[4][3]}]
set_load -pin_load 0 [get_ports {tpu_out[4][2]}]
set_load -pin_load 0 [get_ports {tpu_out[4][1]}]
set_load -pin_load 0 [get_ports {tpu_out[4][0]}]
set_load -pin_load 0 [get_ports {tpu_out[5][31]}]
set_load -pin_load 0 [get_ports {tpu_out[5][30]}]
set_load -pin_load 0 [get_ports {tpu_out[5][29]}]
set_load -pin_load 0 [get_ports {tpu_out[5][28]}]
set_load -pin_load 0 [get_ports {tpu_out[5][27]}]
set_load -pin_load 0 [get_ports {tpu_out[5][26]}]
set_load -pin_load 0 [get_ports {tpu_out[5][25]}]
set_load -pin_load 0 [get_ports {tpu_out[5][24]}]
set_load -pin_load 0 [get_ports {tpu_out[5][23]}]
set_load -pin_load 0 [get_ports {tpu_out[5][22]}]
set_load -pin_load 0 [get_ports {tpu_out[5][21]}]
set_load -pin_load 0 [get_ports {tpu_out[5][20]}]
set_load -pin_load 0 [get_ports {tpu_out[5][19]}]
set_load -pin_load 0 [get_ports {tpu_out[5][18]}]
set_load -pin_load 0 [get_ports {tpu_out[5][17]}]
set_load -pin_load 0 [get_ports {tpu_out[5][16]}]
set_load -pin_load 0 [get_ports {tpu_out[5][15]}]
set_load -pin_load 0 [get_ports {tpu_out[5][14]}]
set_load -pin_load 0 [get_ports {tpu_out[5][13]}]
set_load -pin_load 0 [get_ports {tpu_out[5][12]}]
set_load -pin_load 0 [get_ports {tpu_out[5][11]}]
set_load -pin_load 0 [get_ports {tpu_out[5][10]}]
set_load -pin_load 0 [get_ports {tpu_out[5][9]}]
set_load -pin_load 0 [get_ports {tpu_out[5][8]}]
set_load -pin_load 0 [get_ports {tpu_out[5][7]}]
set_load -pin_load 0 [get_ports {tpu_out[5][6]}]
set_load -pin_load 0 [get_ports {tpu_out[5][5]}]
set_load -pin_load 0 [get_ports {tpu_out[5][4]}]
set_load -pin_load 0 [get_ports {tpu_out[5][3]}]
set_load -pin_load 0 [get_ports {tpu_out[5][2]}]
set_load -pin_load 0 [get_ports {tpu_out[5][1]}]
set_load -pin_load 0 [get_ports {tpu_out[5][0]}]
set_load -pin_load 0 [get_ports {tpu_out[6][31]}]
set_load -pin_load 0 [get_ports {tpu_out[6][30]}]
set_load -pin_load 0 [get_ports {tpu_out[6][29]}]
set_load -pin_load 0 [get_ports {tpu_out[6][28]}]
set_load -pin_load 0 [get_ports {tpu_out[6][27]}]
set_load -pin_load 0 [get_ports {tpu_out[6][26]}]
set_load -pin_load 0 [get_ports {tpu_out[6][25]}]
set_load -pin_load 0 [get_ports {tpu_out[6][24]}]
set_load -pin_load 0 [get_ports {tpu_out[6][23]}]
set_load -pin_load 0 [get_ports {tpu_out[6][22]}]
set_load -pin_load 0 [get_ports {tpu_out[6][21]}]
set_load -pin_load 0 [get_ports {tpu_out[6][20]}]
set_load -pin_load 0 [get_ports {tpu_out[6][19]}]
set_load -pin_load 0 [get_ports {tpu_out[6][18]}]
set_load -pin_load 0 [get_ports {tpu_out[6][17]}]
set_load -pin_load 0 [get_ports {tpu_out[6][16]}]
set_load -pin_load 0 [get_ports {tpu_out[6][15]}]
set_load -pin_load 0 [get_ports {tpu_out[6][14]}]
set_load -pin_load 0 [get_ports {tpu_out[6][13]}]
set_load -pin_load 0 [get_ports {tpu_out[6][12]}]
set_load -pin_load 0 [get_ports {tpu_out[6][11]}]
set_load -pin_load 0 [get_ports {tpu_out[6][10]}]
set_load -pin_load 0 [get_ports {tpu_out[6][9]}]
set_load -pin_load 0 [get_ports {tpu_out[6][8]}]
set_load -pin_load 0 [get_ports {tpu_out[6][7]}]
set_load -pin_load 0 [get_ports {tpu_out[6][6]}]
set_load -pin_load 0 [get_ports {tpu_out[6][5]}]
set_load -pin_load 0 [get_ports {tpu_out[6][4]}]
set_load -pin_load 0 [get_ports {tpu_out[6][3]}]
set_load -pin_load 0 [get_ports {tpu_out[6][2]}]
set_load -pin_load 0 [get_ports {tpu_out[6][1]}]
set_load -pin_load 0 [get_ports {tpu_out[6][0]}]
set_load -pin_load 0 [get_ports {tpu_out[7][31]}]
set_load -pin_load 0 [get_ports {tpu_out[7][30]}]
set_load -pin_load 0 [get_ports {tpu_out[7][29]}]
set_load -pin_load 0 [get_ports {tpu_out[7][28]}]
set_load -pin_load 0 [get_ports {tpu_out[7][27]}]
set_load -pin_load 0 [get_ports {tpu_out[7][26]}]
set_load -pin_load 0 [get_ports {tpu_out[7][25]}]
set_load -pin_load 0 [get_ports {tpu_out[7][24]}]
set_load -pin_load 0 [get_ports {tpu_out[7][23]}]
set_load -pin_load 0 [get_ports {tpu_out[7][22]}]
set_load -pin_load 0 [get_ports {tpu_out[7][21]}]
set_load -pin_load 0 [get_ports {tpu_out[7][20]}]
set_load -pin_load 0 [get_ports {tpu_out[7][19]}]
set_load -pin_load 0 [get_ports {tpu_out[7][18]}]
set_load -pin_load 0 [get_ports {tpu_out[7][17]}]
set_load -pin_load 0 [get_ports {tpu_out[7][16]}]
set_load -pin_load 0 [get_ports {tpu_out[7][15]}]
set_load -pin_load 0 [get_ports {tpu_out[7][14]}]
set_load -pin_load 0 [get_ports {tpu_out[7][13]}]
set_load -pin_load 0 [get_ports {tpu_out[7][12]}]
set_load -pin_load 0 [get_ports {tpu_out[7][11]}]
set_load -pin_load 0 [get_ports {tpu_out[7][10]}]
set_load -pin_load 0 [get_ports {tpu_out[7][9]}]
set_load -pin_load 0 [get_ports {tpu_out[7][8]}]
set_load -pin_load 0 [get_ports {tpu_out[7][7]}]
set_load -pin_load 0 [get_ports {tpu_out[7][6]}]
set_load -pin_load 0 [get_ports {tpu_out[7][5]}]
set_load -pin_load 0 [get_ports {tpu_out[7][4]}]
set_load -pin_load 0 [get_ports {tpu_out[7][3]}]
set_load -pin_load 0 [get_ports {tpu_out[7][2]}]
set_load -pin_load 0 [get_ports {tpu_out[7][1]}]
set_load -pin_load 0 [get_ports {tpu_out[7][0]}]
set_load -pin_load 0 [get_ports {tpu_out[8][31]}]
set_load -pin_load 0 [get_ports {tpu_out[8][30]}]
set_load -pin_load 0 [get_ports {tpu_out[8][29]}]
set_load -pin_load 0 [get_ports {tpu_out[8][28]}]
set_load -pin_load 0 [get_ports {tpu_out[8][27]}]
set_load -pin_load 0 [get_ports {tpu_out[8][26]}]
set_load -pin_load 0 [get_ports {tpu_out[8][25]}]
set_load -pin_load 0 [get_ports {tpu_out[8][24]}]
set_load -pin_load 0 [get_ports {tpu_out[8][23]}]
set_load -pin_load 0 [get_ports {tpu_out[8][22]}]
set_load -pin_load 0 [get_ports {tpu_out[8][21]}]
set_load -pin_load 0 [get_ports {tpu_out[8][20]}]
set_load -pin_load 0 [get_ports {tpu_out[8][19]}]
set_load -pin_load 0 [get_ports {tpu_out[8][18]}]
set_load -pin_load 0 [get_ports {tpu_out[8][17]}]
set_load -pin_load 0 [get_ports {tpu_out[8][16]}]
set_load -pin_load 0 [get_ports {tpu_out[8][15]}]
set_load -pin_load 0 [get_ports {tpu_out[8][14]}]
set_load -pin_load 0 [get_ports {tpu_out[8][13]}]
set_load -pin_load 0 [get_ports {tpu_out[8][12]}]
set_load -pin_load 0 [get_ports {tpu_out[8][11]}]
set_load -pin_load 0 [get_ports {tpu_out[8][10]}]
set_load -pin_load 0 [get_ports {tpu_out[8][9]}]
set_load -pin_load 0 [get_ports {tpu_out[8][8]}]
set_load -pin_load 0 [get_ports {tpu_out[8][7]}]
set_load -pin_load 0 [get_ports {tpu_out[8][6]}]
set_load -pin_load 0 [get_ports {tpu_out[8][5]}]
set_load -pin_load 0 [get_ports {tpu_out[8][4]}]
set_load -pin_load 0 [get_ports {tpu_out[8][3]}]
set_load -pin_load 0 [get_ports {tpu_out[8][2]}]
set_load -pin_load 0 [get_ports {tpu_out[8][1]}]
set_load -pin_load 0 [get_ports {tpu_out[8][0]}]
set_load -pin_load 0 [get_ports {tpu_out[9][31]}]
set_load -pin_load 0 [get_ports {tpu_out[9][30]}]
set_load -pin_load 0 [get_ports {tpu_out[9][29]}]
set_load -pin_load 0 [get_ports {tpu_out[9][28]}]
set_load -pin_load 0 [get_ports {tpu_out[9][27]}]
set_load -pin_load 0 [get_ports {tpu_out[9][26]}]
set_load -pin_load 0 [get_ports {tpu_out[9][25]}]
set_load -pin_load 0 [get_ports {tpu_out[9][24]}]
set_load -pin_load 0 [get_ports {tpu_out[9][23]}]
set_load -pin_load 0 [get_ports {tpu_out[9][22]}]
set_load -pin_load 0 [get_ports {tpu_out[9][21]}]
set_load -pin_load 0 [get_ports {tpu_out[9][20]}]
set_load -pin_load 0 [get_ports {tpu_out[9][19]}]
set_load -pin_load 0 [get_ports {tpu_out[9][18]}]
set_load -pin_load 0 [get_ports {tpu_out[9][17]}]
set_load -pin_load 0 [get_ports {tpu_out[9][16]}]
set_load -pin_load 0 [get_ports {tpu_out[9][15]}]
set_load -pin_load 0 [get_ports {tpu_out[9][14]}]
set_load -pin_load 0 [get_ports {tpu_out[9][13]}]
set_load -pin_load 0 [get_ports {tpu_out[9][12]}]
set_load -pin_load 0 [get_ports {tpu_out[9][11]}]
set_load -pin_load 0 [get_ports {tpu_out[9][10]}]
set_load -pin_load 0 [get_ports {tpu_out[9][9]}]
set_load -pin_load 0 [get_ports {tpu_out[9][8]}]
set_load -pin_load 0 [get_ports {tpu_out[9][7]}]
set_load -pin_load 0 [get_ports {tpu_out[9][6]}]
set_load -pin_load 0 [get_ports {tpu_out[9][5]}]
set_load -pin_load 0 [get_ports {tpu_out[9][4]}]
set_load -pin_load 0 [get_ports {tpu_out[9][3]}]
set_load -pin_load 0 [get_ports {tpu_out[9][2]}]
set_load -pin_load 0 [get_ports {tpu_out[9][1]}]
set_load -pin_load 0 [get_ports {tpu_out[9][0]}]
set_load -pin_load 0 [get_ports {tpu_out[10][31]}]
set_load -pin_load 0 [get_ports {tpu_out[10][30]}]
set_load -pin_load 0 [get_ports {tpu_out[10][29]}]
set_load -pin_load 0 [get_ports {tpu_out[10][28]}]
set_load -pin_load 0 [get_ports {tpu_out[10][27]}]
set_load -pin_load 0 [get_ports {tpu_out[10][26]}]
set_load -pin_load 0 [get_ports {tpu_out[10][25]}]
set_load -pin_load 0 [get_ports {tpu_out[10][24]}]
set_load -pin_load 0 [get_ports {tpu_out[10][23]}]
set_load -pin_load 0 [get_ports {tpu_out[10][22]}]
set_load -pin_load 0 [get_ports {tpu_out[10][21]}]
set_load -pin_load 0 [get_ports {tpu_out[10][20]}]
set_load -pin_load 0 [get_ports {tpu_out[10][19]}]
set_load -pin_load 0 [get_ports {tpu_out[10][18]}]
set_load -pin_load 0 [get_ports {tpu_out[10][17]}]
set_load -pin_load 0 [get_ports {tpu_out[10][16]}]
set_load -pin_load 0 [get_ports {tpu_out[10][15]}]
set_load -pin_load 0 [get_ports {tpu_out[10][14]}]
set_load -pin_load 0 [get_ports {tpu_out[10][13]}]
set_load -pin_load 0 [get_ports {tpu_out[10][12]}]
set_load -pin_load 0 [get_ports {tpu_out[10][11]}]
set_load -pin_load 0 [get_ports {tpu_out[10][10]}]
set_load -pin_load 0 [get_ports {tpu_out[10][9]}]
set_load -pin_load 0 [get_ports {tpu_out[10][8]}]
set_load -pin_load 0 [get_ports {tpu_out[10][7]}]
set_load -pin_load 0 [get_ports {tpu_out[10][6]}]
set_load -pin_load 0 [get_ports {tpu_out[10][5]}]
set_load -pin_load 0 [get_ports {tpu_out[10][4]}]
set_load -pin_load 0 [get_ports {tpu_out[10][3]}]
set_load -pin_load 0 [get_ports {tpu_out[10][2]}]
set_load -pin_load 0 [get_ports {tpu_out[10][1]}]
set_load -pin_load 0 [get_ports {tpu_out[10][0]}]
set_load -pin_load 0 [get_ports {tpu_out[11][31]}]
set_load -pin_load 0 [get_ports {tpu_out[11][30]}]
set_load -pin_load 0 [get_ports {tpu_out[11][29]}]
set_load -pin_load 0 [get_ports {tpu_out[11][28]}]
set_load -pin_load 0 [get_ports {tpu_out[11][27]}]
set_load -pin_load 0 [get_ports {tpu_out[11][26]}]
set_load -pin_load 0 [get_ports {tpu_out[11][25]}]
set_load -pin_load 0 [get_ports {tpu_out[11][24]}]
set_load -pin_load 0 [get_ports {tpu_out[11][23]}]
set_load -pin_load 0 [get_ports {tpu_out[11][22]}]
set_load -pin_load 0 [get_ports {tpu_out[11][21]}]
set_load -pin_load 0 [get_ports {tpu_out[11][20]}]
set_load -pin_load 0 [get_ports {tpu_out[11][19]}]
set_load -pin_load 0 [get_ports {tpu_out[11][18]}]
set_load -pin_load 0 [get_ports {tpu_out[11][17]}]
set_load -pin_load 0 [get_ports {tpu_out[11][16]}]
set_load -pin_load 0 [get_ports {tpu_out[11][15]}]
set_load -pin_load 0 [get_ports {tpu_out[11][14]}]
set_load -pin_load 0 [get_ports {tpu_out[11][13]}]
set_load -pin_load 0 [get_ports {tpu_out[11][12]}]
set_load -pin_load 0 [get_ports {tpu_out[11][11]}]
set_load -pin_load 0 [get_ports {tpu_out[11][10]}]
set_load -pin_load 0 [get_ports {tpu_out[11][9]}]
set_load -pin_load 0 [get_ports {tpu_out[11][8]}]
set_load -pin_load 0 [get_ports {tpu_out[11][7]}]
set_load -pin_load 0 [get_ports {tpu_out[11][6]}]
set_load -pin_load 0 [get_ports {tpu_out[11][5]}]
set_load -pin_load 0 [get_ports {tpu_out[11][4]}]
set_load -pin_load 0 [get_ports {tpu_out[11][3]}]
set_load -pin_load 0 [get_ports {tpu_out[11][2]}]
set_load -pin_load 0 [get_ports {tpu_out[11][1]}]
set_load -pin_load 0 [get_ports {tpu_out[11][0]}]
set_load -pin_load 0 [get_ports {tpu_out[12][31]}]
set_load -pin_load 0 [get_ports {tpu_out[12][30]}]
set_load -pin_load 0 [get_ports {tpu_out[12][29]}]
set_load -pin_load 0 [get_ports {tpu_out[12][28]}]
set_load -pin_load 0 [get_ports {tpu_out[12][27]}]
set_load -pin_load 0 [get_ports {tpu_out[12][26]}]
set_load -pin_load 0 [get_ports {tpu_out[12][25]}]
set_load -pin_load 0 [get_ports {tpu_out[12][24]}]
set_load -pin_load 0 [get_ports {tpu_out[12][23]}]
set_load -pin_load 0 [get_ports {tpu_out[12][22]}]
set_load -pin_load 0 [get_ports {tpu_out[12][21]}]
set_load -pin_load 0 [get_ports {tpu_out[12][20]}]
set_load -pin_load 0 [get_ports {tpu_out[12][19]}]
set_load -pin_load 0 [get_ports {tpu_out[12][18]}]
set_load -pin_load 0 [get_ports {tpu_out[12][17]}]
set_load -pin_load 0 [get_ports {tpu_out[12][16]}]
set_load -pin_load 0 [get_ports {tpu_out[12][15]}]
set_load -pin_load 0 [get_ports {tpu_out[12][14]}]
set_load -pin_load 0 [get_ports {tpu_out[12][13]}]
set_load -pin_load 0 [get_ports {tpu_out[12][12]}]
set_load -pin_load 0 [get_ports {tpu_out[12][11]}]
set_load -pin_load 0 [get_ports {tpu_out[12][10]}]
set_load -pin_load 0 [get_ports {tpu_out[12][9]}]
set_load -pin_load 0 [get_ports {tpu_out[12][8]}]
set_load -pin_load 0 [get_ports {tpu_out[12][7]}]
set_load -pin_load 0 [get_ports {tpu_out[12][6]}]
set_load -pin_load 0 [get_ports {tpu_out[12][5]}]
set_load -pin_load 0 [get_ports {tpu_out[12][4]}]
set_load -pin_load 0 [get_ports {tpu_out[12][3]}]
set_load -pin_load 0 [get_ports {tpu_out[12][2]}]
set_load -pin_load 0 [get_ports {tpu_out[12][1]}]
set_load -pin_load 0 [get_ports {tpu_out[12][0]}]
set_load -pin_load 0 [get_ports {tpu_out[13][31]}]
set_load -pin_load 0 [get_ports {tpu_out[13][30]}]
set_load -pin_load 0 [get_ports {tpu_out[13][29]}]
set_load -pin_load 0 [get_ports {tpu_out[13][28]}]
set_load -pin_load 0 [get_ports {tpu_out[13][27]}]
set_load -pin_load 0 [get_ports {tpu_out[13][26]}]
set_load -pin_load 0 [get_ports {tpu_out[13][25]}]
set_load -pin_load 0 [get_ports {tpu_out[13][24]}]
set_load -pin_load 0 [get_ports {tpu_out[13][23]}]
set_load -pin_load 0 [get_ports {tpu_out[13][22]}]
set_load -pin_load 0 [get_ports {tpu_out[13][21]}]
set_load -pin_load 0 [get_ports {tpu_out[13][20]}]
set_load -pin_load 0 [get_ports {tpu_out[13][19]}]
set_load -pin_load 0 [get_ports {tpu_out[13][18]}]
set_load -pin_load 0 [get_ports {tpu_out[13][17]}]
set_load -pin_load 0 [get_ports {tpu_out[13][16]}]
set_load -pin_load 0 [get_ports {tpu_out[13][15]}]
set_load -pin_load 0 [get_ports {tpu_out[13][14]}]
set_load -pin_load 0 [get_ports {tpu_out[13][13]}]
set_load -pin_load 0 [get_ports {tpu_out[13][12]}]
set_load -pin_load 0 [get_ports {tpu_out[13][11]}]
set_load -pin_load 0 [get_ports {tpu_out[13][10]}]
set_load -pin_load 0 [get_ports {tpu_out[13][9]}]
set_load -pin_load 0 [get_ports {tpu_out[13][8]}]
set_load -pin_load 0 [get_ports {tpu_out[13][7]}]
set_load -pin_load 0 [get_ports {tpu_out[13][6]}]
set_load -pin_load 0 [get_ports {tpu_out[13][5]}]
set_load -pin_load 0 [get_ports {tpu_out[13][4]}]
set_load -pin_load 0 [get_ports {tpu_out[13][3]}]
set_load -pin_load 0 [get_ports {tpu_out[13][2]}]
set_load -pin_load 0 [get_ports {tpu_out[13][1]}]
set_load -pin_load 0 [get_ports {tpu_out[13][0]}]
set_load -pin_load 0 [get_ports {tpu_out[14][31]}]
set_load -pin_load 0 [get_ports {tpu_out[14][30]}]
set_load -pin_load 0 [get_ports {tpu_out[14][29]}]
set_load -pin_load 0 [get_ports {tpu_out[14][28]}]
set_load -pin_load 0 [get_ports {tpu_out[14][27]}]
set_load -pin_load 0 [get_ports {tpu_out[14][26]}]
set_load -pin_load 0 [get_ports {tpu_out[14][25]}]
set_load -pin_load 0 [get_ports {tpu_out[14][24]}]
set_load -pin_load 0 [get_ports {tpu_out[14][23]}]
set_load -pin_load 0 [get_ports {tpu_out[14][22]}]
set_load -pin_load 0 [get_ports {tpu_out[14][21]}]
set_load -pin_load 0 [get_ports {tpu_out[14][20]}]
set_load -pin_load 0 [get_ports {tpu_out[14][19]}]
set_load -pin_load 0 [get_ports {tpu_out[14][18]}]
set_load -pin_load 0 [get_ports {tpu_out[14][17]}]
set_load -pin_load 0 [get_ports {tpu_out[14][16]}]
set_load -pin_load 0 [get_ports {tpu_out[14][15]}]
set_load -pin_load 0 [get_ports {tpu_out[14][14]}]
set_load -pin_load 0 [get_ports {tpu_out[14][13]}]
set_load -pin_load 0 [get_ports {tpu_out[14][12]}]
set_load -pin_load 0 [get_ports {tpu_out[14][11]}]
set_load -pin_load 0 [get_ports {tpu_out[14][10]}]
set_load -pin_load 0 [get_ports {tpu_out[14][9]}]
set_load -pin_load 0 [get_ports {tpu_out[14][8]}]
set_load -pin_load 0 [get_ports {tpu_out[14][7]}]
set_load -pin_load 0 [get_ports {tpu_out[14][6]}]
set_load -pin_load 0 [get_ports {tpu_out[14][5]}]
set_load -pin_load 0 [get_ports {tpu_out[14][4]}]
set_load -pin_load 0 [get_ports {tpu_out[14][3]}]
set_load -pin_load 0 [get_ports {tpu_out[14][2]}]
set_load -pin_load 0 [get_ports {tpu_out[14][1]}]
set_load -pin_load 0 [get_ports {tpu_out[14][0]}]
set_load -pin_load 0 [get_ports {tpu_out[15][31]}]
set_load -pin_load 0 [get_ports {tpu_out[15][30]}]
set_load -pin_load 0 [get_ports {tpu_out[15][29]}]
set_load -pin_load 0 [get_ports {tpu_out[15][28]}]
set_load -pin_load 0 [get_ports {tpu_out[15][27]}]
set_load -pin_load 0 [get_ports {tpu_out[15][26]}]
set_load -pin_load 0 [get_ports {tpu_out[15][25]}]
set_load -pin_load 0 [get_ports {tpu_out[15][24]}]
set_load -pin_load 0 [get_ports {tpu_out[15][23]}]
set_load -pin_load 0 [get_ports {tpu_out[15][22]}]
set_load -pin_load 0 [get_ports {tpu_out[15][21]}]
set_load -pin_load 0 [get_ports {tpu_out[15][20]}]
set_load -pin_load 0 [get_ports {tpu_out[15][19]}]
set_load -pin_load 0 [get_ports {tpu_out[15][18]}]
set_load -pin_load 0 [get_ports {tpu_out[15][17]}]
set_load -pin_load 0 [get_ports {tpu_out[15][16]}]
set_load -pin_load 0 [get_ports {tpu_out[15][15]}]
set_load -pin_load 0 [get_ports {tpu_out[15][14]}]
set_load -pin_load 0 [get_ports {tpu_out[15][13]}]
set_load -pin_load 0 [get_ports {tpu_out[15][12]}]
set_load -pin_load 0 [get_ports {tpu_out[15][11]}]
set_load -pin_load 0 [get_ports {tpu_out[15][10]}]
set_load -pin_load 0 [get_ports {tpu_out[15][9]}]
set_load -pin_load 0 [get_ports {tpu_out[15][8]}]
set_load -pin_load 0 [get_ports {tpu_out[15][7]}]
set_load -pin_load 0 [get_ports {tpu_out[15][6]}]
set_load -pin_load 0 [get_ports {tpu_out[15][5]}]
set_load -pin_load 0 [get_ports {tpu_out[15][4]}]
set_load -pin_load 0 [get_ports {tpu_out[15][3]}]
set_load -pin_load 0 [get_ports {tpu_out[15][2]}]
set_load -pin_load 0 [get_ports {tpu_out[15][1]}]
set_load -pin_load 0 [get_ports {tpu_out[15][0]}]
create_clock [get_ports clk]  -period 5  -waveform {0 2.5}
set_clock_uncertainty 0.05  [get_clocks clk]
set_input_delay -clock clk  0.1  [get_ports rst_n]
set_input_delay -clock clk  0.1  [get_ports wt_sram_wen]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[7]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[6]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[5]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[4]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[3]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[2]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[1]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_waddr[0]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[15]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[14]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[13]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[12]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[11]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[10]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[9]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[8]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[7]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[6]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[5]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[4]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[3]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[2]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[1]}]
set_input_delay -clock clk  0.1  [get_ports {wt_sram_wdata[0]}]
set_input_delay -clock clk  0.1  [get_ports start_weight_load]
set_input_delay -clock clk  0.1  [get_ports act_sram_wen]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[9]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[8]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[7]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[6]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[5]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[4]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[3]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[2]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[1]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_waddr[0]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[255]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[254]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[253]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[252]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[251]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[250]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[249]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[248]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[247]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[246]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[245]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[244]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[243]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[242]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[241]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[240]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[239]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[238]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[237]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[236]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[235]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[234]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[233]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[232]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[231]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[230]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[229]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[228]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[227]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[226]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[225]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[224]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[223]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[222]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[221]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[220]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[219]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[218]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[217]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[216]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[215]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[214]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[213]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[212]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[211]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[210]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[209]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[208]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[207]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[206]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[205]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[204]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[203]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[202]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[201]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[200]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[199]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[198]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[197]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[196]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[195]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[194]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[193]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[192]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[191]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[190]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[189]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[188]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[187]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[186]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[185]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[184]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[183]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[182]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[181]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[180]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[179]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[178]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[177]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[176]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[175]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[174]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[173]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[172]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[171]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[170]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[169]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[168]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[167]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[166]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[165]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[164]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[163]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[162]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[161]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[160]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[159]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[158]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[157]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[156]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[155]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[154]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[153]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[152]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[151]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[150]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[149]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[148]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[147]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[146]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[145]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[144]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[143]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[142]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[141]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[140]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[139]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[138]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[137]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[136]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[135]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[134]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[133]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[132]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[131]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[130]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[129]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[128]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[127]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[126]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[125]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[124]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[123]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[122]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[121]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[120]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[119]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[118]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[117]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[116]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[115]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[114]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[113]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[112]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[111]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[110]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[109]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[108]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[107]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[106]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[105]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[104]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[103]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[102]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[101]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[100]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[99]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[98]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[97]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[96]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[95]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[94]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[93]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[92]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[91]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[90]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[89]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[88]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[87]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[86]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[85]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[84]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[83]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[82]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[81]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[80]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[79]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[78]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[77]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[76]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[75]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[74]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[73]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[72]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[71]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[70]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[69]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[68]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[67]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[66]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[65]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[64]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[63]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[62]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[61]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[60]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[59]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[58]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[57]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[56]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[55]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[54]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[53]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[52]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[51]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[50]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[49]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[48]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[47]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[46]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[45]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[44]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[43]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[42]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[41]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[40]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[39]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[38]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[37]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[36]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[35]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[34]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[33]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[32]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[31]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[30]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[29]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[28]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[27]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[26]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[25]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[24]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[23]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[22]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[21]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[20]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[19]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[18]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[17]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[16]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[15]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[14]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[13]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[12]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[11]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[10]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[9]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[8]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[7]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[6]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[5]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[4]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[3]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[2]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[1]}]
set_input_delay -clock clk  0.1  [get_ports {act_sram_wdata[0]}]
set_input_delay -clock clk  0.1  [get_ports start_exec]
set_output_delay -clock clk  0.4  [get_ports weight_load_done]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[0][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[1][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[2][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[3][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[4][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[5][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[6][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[7][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[8][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[9][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[10][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[11][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[12][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[13][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[14][0]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][31]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][30]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][29]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][28]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][27]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][26]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][25]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][24]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][23]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][22]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][21]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][20]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][19]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][18]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][17]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][16]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][15]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][14]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][13]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][12]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][11]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][10]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][9]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][8]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][7]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][6]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][5]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][4]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][3]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][2]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][1]}]
set_output_delay -clock clk  0.4  [get_ports {tpu_out[15][0]}]
